version: '2'
services:
  reportesuno-app:
    image: reportesuno
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://reportesuno-postgresql:5432/reportesUno
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://reportesuno-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://reportesuno-elasticsearch:9200
    ports:
      - 8080:8080
  reportesuno-postgresql:
    extends:
      file: postgresql.yml
      service: reportesuno-postgresql
  reportesuno-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: reportesuno-elasticsearch
